### ISSUE TITLE
Support Editorial Stream document processing

### ISSUE THREAD

**Issue by rjsparks** [ietf-tools/roadmap-deprecated-2025#3]
```[tasklist]
- [ ] https://github.com/ietf-tools/xml2rfc/issues/896
- [ ] https://github.com/ietf-tools/datatracker/issues/4333
- [ ] https://github.com/ietf-tools/bibxml-service/issues/301
```
